FROM node:7.4
MAINTAINER R. Mark Volkmann
#CMD node -v
#CMD ["node", "-v"]

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

# Bundle app source
COPY . /usr/src/app

# List ports to expose for servers.
#EXPOSE 8080

#CMD "npm start" # This does not work.
CMD ["npm", "--silent", "start"]
